### PR TITLE
Make KFENCE summary more crisp

### LINKED ISSUE #216: Move KFENCE internals info to kernel docs
Currently, KFENCE.md contains information that possibly extends/duplicates kernel's documentation about KFENCE. It makes sense to move/drop this duplicate information from KFENCE.md.

### PR DESCRIPTION
**Pull request by melver**
To resolve https://github.com/google/kernel-sanitizers/issues/216

### CODE REVIEW

**Comment by xairy** [comment]
I would add a sentence saying that on allocation, with a small probability, KFENCE redirects the allocator to use one of those guarded object.

**Comment by melver** [comment]
> I would add a sentence saying that on allocation, with a small probability, KFENCE redirects the allocator to use one of those guarded object.

Done.

**Comment by xairy** [comment]
I still feel like a part of logic is missing :)

Paragraph 1 focuses on "KFENCE allocates guarded pages".

Paragraph 2 focuses on "Guarded pages are expensive".

There should a piece in between focusing on "On allocation, KFENCE places objects into these guarded pages".

Paragraph 3 looks great.

**Comment by melver** [comment]
PTAL

**Review by xairy — APPROVED** [review]

**Pull request merged**
